# Generated by Django 5.0.7 on 2024-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название курса",
                        max_length=100,
                        verbose_name="название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/course_preview/",
                        verbose_name="превью курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="введите описание курса",
                        null=True,
                        verbose_name="описание курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_name",
                    models.CharField(max_length=100, verbose_name="название урока"),
                ),
                (
                    "lesson_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание урока"
                    ),
                ),
                (
                    "lesson_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/lesson_preview",
                        verbose_name="изображение урока",
                    ),
                ),
                (
                    "lesson_url",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="ссылка на видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
